# Any configuration that is not specific for any environment should be placed in this file.

server:
  port: 3000

db:
  port: 5432
  database: taskmanagement
  autoLoadEntities: true

jwt:
  expiresIn: 3600
